dist: trusty
language: rust

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: 1.31.0

    - rust: nightly
      script:
        - cargo update -Zminimal-versions
        - cargo check

before_install: set -e

install:
  - source ~/.cargo/env || true

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
script:
  - cargo build 
  - RUST_BACKTRACE=1 cargo test test_fcntl::test_readlink

notifications:
  email:
    on_success: never
