dist: trusty
language: rust

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=arm-unknown-linux-gnueabi
      rust: 1.31.0
    - env: TARGET=arm-unknown-linux-musleabi DISABLE_TESTS=1
      rust: 1.31.0
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: 1.31.0
    - env: TARGET=i686-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=i686-unknown-linux-musl
      rust: 1.31.0
    - env: TARGET=mips-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=mips64-unknown-linux-gnuabi64
      rust: 1.31.0
    - env: TARGET=mips64el-unknown-linux-gnuabi64
      rust: 1.31.0
    - env: TARGET=mipsel-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=powerpc-unknown-linux-gnu DISABLE_TESTS=1
      rust: 1.31.0
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=powerpc64le-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
      rust: 1.31.0
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.31.0
    - env: TARGET=x86_64-unknown-linux-musl
      rust: 1.31.0

    - rust: nightly
      script:
        - cargo update -Zminimal-versions
        - cargo check

before_install: set -e

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
